version: "3"
services:
  syncplay-server:
    build: ..
    restart_policy: on-failure
    ports:
      - "8999:8999"
    command:
      - "--password=<You should add your own password here>"
      - "--salt=LKAJSDLOJSDA"
      - "--tls=/app/syncplay/certs/..."
    volumes:
      - <path to certs>:/app/syncplay/certs
